#Alexa Pollard (21075914)

import random
answer=random.randint(0,100)

def guessing_game():
    'This function allows the user to guess a random number generated by the program until they get it right'
    guess = -1
    while guess != answer:
        guess=input("Please enter a number: ")
        if(not guess.isdigit()):
            print("Invalid Input")
            return None
        guess = int(guess)
        if guess<answer:
            print("Your guess was too low")
        elif guess>answer:
            print("Your guess was too high")
        
    print("You got the answer!")

guessing_game()






